<?php
//Get System Constants
require("./AJAX/sysConstants.php");
$loop = Constant::getGAME_COUNT();//Get number of games loaded into system

///////////////////////////////////////////////////////////////////////////////////		Generate Javascript
//Start Javascript generation
	$javascript = "<script type='text/javascript'>/*Automatically Generated by server*/
			document.addEventListener('DOMContentLoaded', function(){
				document.getElementById('#cstm').addEventListener('change', handleEdit);";
//Add event listeners to elements
	for($i=0;$i<$loop;$i++){
		$javascript .= "document.getElementById('#".$i."cost').addEventListener('change',handleEdit);";
	}
//Create handleEdit Script to combine values for current purchase total
	$javascript .= "});
	function handleEdit(){
		window.location.href='http://" .  $_SERVER['SERVER_ADDR'] . "/2016/TSA/accountManager.php#mainBody';
		var ic = document.getElementById('#cstm').value.trim() == '' ? parseInt(0) : document.getElementById('#cstm').value;";
	
	for($i=0;$i<$loop;$i++){
		$javascript .= "var i".$i." = document.getElementById('#".$i."cost').value;";
	}
	$javascript .= "var total = parseFloat(";
	for($i=0;$i<$loop;$i++){	
		$javascript .= "parseFloat(i".$i.") +"; 
	}
	$javascript .= "parseFloat(ic)).toFixed(2);document.getElementById('#total').innerHTML = '$' + total;}";
	$javascript .= "</script>";
////////////////////////////////////////////////////////////////////////////////////	Generate HTML Formating
	$html = "<form action='./transHandler.php' method='POST'><table><tr>";
	for($i=0;$i<$loop;$i++){//Loop through all games per dictated by COUNT
		if(($i+1) % 3 == 0){$html .= "</tr><tr><td>";}
		else{$html .= "<td>";}
		$gameParam = Constant::getGAME_PARAM($i);
		if($gameParam == null){break;}
		$html .= "<div class='game'><table align='center'><tr><td><h3>" . $gameParam[0] . "</h3></td></tr><tr><td>
		<select name='".$i."cost' id='#".$i."cost'>
			<option value='0'>----</option>";
			foreach($gameParam[1] as $price){//Load options for individual games ([NAME][PRICE[OPTx[DESC,VALUE]]])
				$html .= "<option value='".$price["VALUE"]."'>".$price["DESC"]."</option>";
			}
		$html .= "</select></td></tr></table></div></td>";
	}
	$html .= "</tr></table>";
	//Add Custom Transaction box
	$html .= "<br/>
			<div class='game'>
				<table align='center'>
					<tr><td><h3>Custom Charge</h3></td></tr>
					<tr><td>Amount: <input type='text' name='cstm' id='#cstm' value='' placeholder='ex: 5.40'/></td></tr>
					<tr><td>Comment <input type='text' name='cstmComment' value='' placeholder='Transaction Comment'/></td></tr>
				</table>
			</div>";
?>
<!DOCTYPE html>
<html>
<!--Page is automatically generated by the server on a per-request basis-->
	<head>
		<style type="text/css">
			html{
				background-color: #A3A3C2;
			}
			div.game{
				background-color:#94B8FF;
				width: 300px;
				border: 1px solid white;
			}
			table{
				text-align:center;
			}
		</style>
	</head>
	<body id="#mainBody">
		<center>
			<?php echo $html;?>
			<br/>
			<h3 id='#total'></h3>
			<input style="width:100px;height:50px;font-size:20px;" type='submit' name='charge' value='Charge'/>
			</form>
		</center>
		<?php echo $javascript;?>
	</body>
</html>
